// Platform hooks - device/OS-specific functionality
export {
  usePlatform,
  type Platform,
  useHaptics,
  type HapticStyle,
  type HapticNotification,
  type UseHapticsResult,
  useBiometric,
  type BiometricStatus,
  type UseBiometricResult,
  useQRScanner,
  useNotifications,
  type UseNotificationsResult,
  useAppIcon,
  type IconId,
  type IconVariant,
  type UseAppIconResult,
  useBackgroundTask,
  type UseBackgroundTaskResult,
  useDeepLinks,
  useShareHandler,
  type UseShareHandlerResult,
} from './platform';

// Data hooks - CRUD and data management
export {
  useTasks,
  type UseTasksOptions,
  type UseTasksResult,
  useTemplates,
  type UseTemplatesResult,
  useSearch,
  type UseSearchOptions,
  type UseSearchResult,
  useSearchResults,
  type UseSearchResultsOptions,
  type UseSearchResultsResult,
  type SearchFilters,
  useInbox,
  type UseInboxResult,
  useDailyNote,
  useTodaysDailyNote,
  type UseDailyNoteResult,
  usePinnedObjects,
  type UsePinnedObjectsResult,
  useSavedViews,
  type UseSavedViewsResult,
  useArchive,
  type UseArchiveResult,
  useDuplicate,
  type UseDuplicateResult,
  useLinkToDaily,
} from './data';

// UI hooks - interface state and interactions
export {
  useTheme,
  useSelection,
  type UseSelectionOptions,
  type UseSelectionResult,
  type SelectionState,
  type SelectionActions,
  useScrollDirection,
  type ScrollDirection,
  type UseScrollDirectionOptions,
  type UseScrollDirectionResult,
  useConfirmDialog,
  type ConfirmOptions,
  type ConfirmDialogState,
  type UseConfirmDialogResult,
  useContextMenu,
  type ContextMenuPosition,
  type UseContextMenuResult,
  useReducedMotion,
  getAccessibleTransition,
  useUndoToast,
  useCalendar,
  type UseCalendarResult,
} from './ui';

// Sync hooks - data synchronization
export {
  useSync,
  useConnectionStatus,
  useSemanticIndexSync,
} from './sync';
